### PR TITLE
Allmatchesindex

### PR DESCRIPTION
**Pull request by edgr**

### CODE REVIEW

**Comment by edgr** [comment]
@florindiconescu some things are a little confusing but seem to work. Can you have a look?

**Comment by edgr** [comment]
I agree with your first remark.
For the second one, I am concerned about the url structure, should I be concerned? Also because I wanted to use /matches for all matches.

**Comment by florindiconescu** [comment]
Can you check your routes now? It might be even not recommended to display in your url something like /users/15/matches, this way you will disclose the id from the db..
I think that is why devise has the helper methods, so you should hide the user id from the url, but you can decide as a developer if you want to display something only if the user_signed_in? or only if user = current_user

**Comment by florindiconescu** [comment]
Just to make sure we are on the same page, nesting is just forcing to pass an id of the parent model/table, i don't think it comes with any extra benefits

**Comment by edgr** [comment]
I am not sure to understand. When on the user show page, indeed the id is in the URL no? If you have a cleaner way, feel free to change it.

**Pull request merged**
